In [1]:
import numpy as np
arr=np.arange(0,11)

In [2]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[3]

3

In [4]:
arr[7:11]

array([ 7,  8,  9, 10])

In [5]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[:3]

array([0, 1, 2])

In [7]:
arr[0:5]=100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr=np.arange(0,11)

In [13]:
slice_of_arr=arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
slicearr=arr.copy()
slicearr[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
slicearr[:]=10
slicearr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
a2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
a2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
a2d[0][0]

5

In [24]:
a2d[0,0]

5

In [25]:
a2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
#[rows,cols]
#[all but row2,all but col2]
a2d[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [27]:
a2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [28]:
ar=np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_ar=ar > 5

In [31]:
bool_ar

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
ar[bool_ar]

array([ 6,  7,  8,  9, 10])

In [33]:
ar[ar>5]

array([ 6,  7,  8,  9, 10])

In [34]:
ar[ar<3]

array([1, 2])

In [35]:
ra=np.arange(50).reshape(5,10)
ra

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
ra[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Exercise
### Write one line code using Numpy to print the following output shown in each cell
### Do not delete the answer shown

In [37]:
import numpy as np

In [44]:
r1=np.zeros(10)
arr=np.zeros((1,11))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
arr1=np.ones((1,11))
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
arr2=arr1*5
arr2

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [50]:
arr3=np.arange(10,51)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [93]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [60]:
arr5=np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr6=np.identity(3)
# np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.random.uniform(size=1)
#np.random.rand(1)

array([0.14378126])

In [68]:
np.random.normal(size=25).reshape(5,5)
np.random.randn(25)

array([[-2.02767032, -0.83912969, -0.50093421, -2.6362676 ,  0.63840132],
       [ 2.03688299,  0.35314987, -0.20669121,  0.80079785, -0.27399966],
       [-0.20352855,  0.3444918 ,  0.96234779,  0.65849386,  0.39166931],
       [ 1.20238253,  0.1215956 ,  0.31129586,  0.45701346, -0.20016717],
       [-0.52460598,  0.73247775, -1.34818403, -0.97298194,  0.10169812]])

In [76]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [77]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [78]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [80]:
mat[3][4]
mat[3,4]

20

In [81]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [82]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [83]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
np.sum(mat)

325

In [85]:
np.std(mat)

7.211102550927978

In [91]:
# column additions
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [92]:
# row additions
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])